export const PLANETS = [
  {
    id: 'profile',
    position: [70, 0, 6],
    size: 5,
    color: '#4422aa',
    ring: null,
    moon: null,
    orbitRadius: 13,
    tags: ['Go', 'Linux', 'Ring 0', 'AI', 'Self-taught'],
  },
  {
    id: 'projects',
    position: [150, 0, -8],
    size: 6,
    color: '#225588',
    ring: '#a9c9ff',
    moon: { orbitRadius: 12, orbitSpeed: 0.3, size: 1.3, color: '#c9c9c9' },
    orbitRadius: 15,
    tags: ['Assembly x86', 'Ring 0', 'Python', 'ML/DL/RL', 'Pygame'],
  },
  {
    id: 'experience',
    position: [230, 0, 5],
    size: 4.5,
    color: '#883355',
    ring: null,
    moon: null,
    orbitRadius: 12,
    tags: ['Backend', 'Architecture', 'Security', 'Agile'],
  },
  {
    id: 'contact',
    position: [310, 0, -6],
    size: 5,
    color: '#2f6f4f',
    ring: '#8fffc2',
    moon: { orbitRadius: 10, orbitSpeed: -0.22, size: 1, color: '#e0e0e0' },
    orbitRadius: 14,
    tags: ['Go', 'C++', 'Assembly', 'Python'],
    isContact: true,
  },
]
